### ISSUE TITLE
attrs version pinning?

### ISSUE THREAD

**Issue by akhanf** [khanlab/snakebids#398]
## The problem

I began getting the following error in a snakebids environment:

```
TypeError in file /local/scratch/snakebatch/workflow/Snakefile, line 1:
field() got an unexpected keyword argument 'alias'
  File "/local/scratch/snakebatch/workflow/Snakefile", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1039, in _handle_fromlist
  File "/localscratch/pypoetry_venv/snakebatch-K9plrFXd-py3.8/lib/python3.8/site-packages/lazy_loader/__init__.py", line 78, in __getattr__
  File "/localscratch/pypoetry_venv/snakebatch-K9plrFXd-py3.8/lib/python3.8/site-packages/lazy_loader/__init__.py", line 77, in __getattr__
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
  File "/localscratch/pypoetry_venv/snakebatch-K9plrFXd-py3.8/lib/python3.8/site-packages/snakebids/core/input_generation.py", line 28, in <module>
  File "/localscratch/pypoetry_venv/snakebatch-K9plrFXd-py3.8/lib/python3.8/site-packages/snakebids/core/datasets.py", line 188, in <module>
  File "/localscratch/pypoetry_venv/snakebatch-K9plrFXd-py3.8/lib/python3.8/site-packages/snakebids/core/datasets.py", line 211, in BidsPartialComponent
```

which was fixed when I upgraded `attrs` from 21.4.0 -> 23.2.0

Haven't dug into it further, but wondering if this needs to be pinned in snakebids?

**Comment by kaitj** [comment]
Hmm, thats strange. It should detect the newer version from the `poetry.lock` file.

Is this being installed as part of [`snakebatch`](https://github.com/akhanf/snakebatch)? Might just be that the `poetry.lock` file there needs to be updated? I see that that one is using `snakebids@^0.9.2`, which should still install `attrs@23.1.0`.

**Comment by akhanf** [comment]
The pyproject file here is the one I was using (latest version of snakebids): 
https://github.com/akhanf/snakebatch/blob/lobe-update/pyproject.toml

**Comment by pvandyken** [comment]
The pyproject allows that version, so nothing weird here. Just a matter of finding the first version of attrs that has `alias`

**Comment by kaitj** [comment]
I tried to run `poetry lock` to update the lock file before running `poetry install` on snakebatch commit `66bb6ac` (the commit before the `attrs` pinning) - it looks like it was able to update to `attrs@23.2.0`. I think maybe running a `poetry install` without it may have picked up the version (`21.4.0`) from the existing lockfile.

I don't think we need to pin the `attrs` version in this case (as Peter noted, the pyproject doesn't have a maximum version pinned).

**Comment by pvandyken** [comment]
No need for a maximum, this is simply a problem of snakebids allowing versions of attrs too old to support all the features we support.

The lock file is not reliable for pip installs in general

**Comment by pvandyken** [comment]
Looks like we need `>=22.2.0` https://www.attrs.org/en/stable/changelog.html#id4
